# .github/workflows/snake.yml
name: Generate Snake

on:
  schedule:
    - cron: "15 30 * * *"  # Runs every midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Sankeerth28
          outputs: |
            dist/github-contribution-grid-snake.svg
      - name: Push Snake
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
